name: CI
on:

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

env:
  flutter_version: '3.0.1'

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.flutter_version }}
          cache: true
          cache-key: flutter
          cache-path: ${{ runner.tool_cache }}/flutter

      - run: echo "${{secrets.ENV_COPY }}" > .env
      - run: flutter pub get

      - id: analyze
        run: flutter analyze

      - if: steps.analyze.conclusion == 'success'
        run: flutter test


