name: clink_mobile_app
description: Cross platform mobile app
publish_to: 'none'
version: 1.1.0+1

environment:
  sdk: '>=2.17.1 <3.0.0'

dependencies:
  carousel_slider: ^4.1.1
  cloud_firestore: ^3.5.0
  cupertino_icons: ^1.0.5
  easy_localization: ^3.0.1
  firebase_core: ^1.24.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.1.0
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  sentry_flutter: ^6.10.0
  syncfusion_flutter_charts: ^20.2.50
  sqflite: ^2.1.0
  uuid: ^3.0.6

dev_dependencies:
  build_runner: ^2.2.1
  flutter_launcher_icons: ^0.10.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  freezed: ^2.1.0+1
  mocktail: ^0.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/images/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"

